# Generated by Django 3.0.2 on 2020-01-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0002_casa_morador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casa',
            old_name='morador',
            new_name='dono',
        ),
    ]
