# Generated by Django 3.0.2 on 2020-01-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_remove_pessoa_casa'),
        ('casas', '0004_auto_20200109_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='dono',
            field=models.ManyToManyField(to='pessoas.Pessoa'),
        ),
    ]
